package routes

import (
	"log"
	"net/http"

	jwt "github.com/appleboy/gin-jwt/v2"
	"github.com/gin-gonic/gin"
	"github.com/sohag1990/Paichi/app/controllers"
	"github.com/sohag1990/Paichi/app/middlewares"
)

// API REST ROUTES
func API(r *gin.Engine) *gin.Engine {
	// adapter := gormadapter.NewAdapterByDB(db.DB)
	// ok, err := enforce(val.(string), obj, act, adapter)
	// bindu generate routes User --group v1 --auth true
	// bindu generate scaffold User --group v1 --auth true
	// bindu generate controller User --group v1 --auth true
	r.StaticFS("/file", http.Dir("public/uploads"))
	r.POST("/uploader", controllers.Uploader)
	r.Use(middlewares.Cors())
	authMiddleware, err := jwt.New(middlewares.GinJwtMiddlewareHandler())
	if err != nil {
		log.Fatal("JWT Error:" + err.Error())
	}
	// r.GET("/posts/:id/comments/:page", controllers.IndexComment)
	r.GET("/lost-items/:page", controllers.LostItem)
	r.GET("/found-items/:page", controllers.FoundItem)
	r.GET("/search-items/:page/:search", controllers.FoundLostItemSearch)
	// r.GET("/items/:page", controllers.IndexItem)
	r.GET("/item/:id", controllers.ShowItem)
	api := r.Group("/api")
	api.POST("/login", authMiddleware.LoginHandler)
	api.POST("/register", controllers.Registration)

	v1 := api.Group("/v1")
	{ //v1 Auth route Start
		v1.GET("/user/:un", controllers.ShowUser)
		v1.GET("/lost-items-few/:page", controllers.LostItem)
		v1.GET("/found-items-few/:page", controllers.FoundItem)
	} //v1 Auth Route end

	v1.Use(authMiddleware.MiddlewareFunc())
	{

		//v1 Routes generated by bindu for Contact

		// v1.GET("/contacts/:page", controllers.IndexContact)
		v1.POST("/contact", controllers.CreateContact)
		// v1.GET("/contact/:id", controllers.ShowContact)
		// v1.PUT("/contact/:id", controllers.UpdateContact)
		// v1.DELETE("/contact/:id", controllers.DestroyContact)

		//v1 Routes generated by bindu for Comment
		v1.GET("/comments/:page", controllers.IndexComment)
		v1.POST("/post/:id/comment", controllers.CreateComment)
		// v1.GET("/comment/:id", controllers.ShowComment)
		v1.PUT("/comment/:id", controllers.UpdateComment)
		v1.DELETE("/comment/:id", controllers.DestroyComment)

		//v1 Routes generated by bindu for Item

		v1.GET("/lost-items/:page", controllers.LostItem)
		v1.GET("/found-items/:page", controllers.FoundItem)
		v1.POST("/item", controllers.CreateItem)
		v1.GET("/item/:id", controllers.ShowItem)
		v1.PUT("/item/:id", controllers.UpdateItem)
		v1.DELETE("/item/:id", controllers.DestroyItem)
		v1.POST("/updateprofileimage", controllers.UpdateProfileImage)

		//v1 Routes generated by bindu for User

		// v1.GET("/users/:page", controllers.IndexUser)
		// v1.POST("/user", controllers.CreateUser)
		// v1.GET("/user/:un", controllers.ShowUser)
		// v1.PUT("/user/:id", controllers.UpdateUser)
		// v1.DELETE("/user/:id", controllers.DestroyUser)

	}
	return r
}
