package models

import "time"

// Item public model generated by bindu
type Item struct {
	Mobile      string
	Description string
	Location    string
	Type        string
	Image       string
	Title       string
	Date        string
	UserID      uint64 `json:"-"`
	User        User
	ID          uint64 `gorm:"primary_key"`
	CreatedAt   time.Time
	UpdatedAt   time.Time  `json:"-"`
	DeletedAt   *time.Time `sql:"index" json:"-"`
	Comments    []Comment  `gorm:"foreignkey:ItemID"`
}
