package models

// User public model generated by bindu
type User struct {
	Items    []Item  `gorm:"foreignkey:UserID"`
	Profile  Profile `gorm:"foreignkey:UserID"`
	Email    string  `gorm:"type:varchar(50);unique_index;default:null`
	Phone    string  `gorm:"type:varchar(50);unique_index;default:null`
	Username string  `form:"username" json:"username" binding:"required";unique_index;default:null`
	Password string  `form:"password" json:"password" binding:"required" json:"-"`
	Role     string  `gorm:"type:varchar(20);unique_index`
	DefaultProperties
}
