package controllers
 
import (

	"github.com/gin-gonic/gin"
	"github.com/sohag1990/Paichi/app/models"
	"github.com/sohag1990/Paichi/db"
)

// Blog public controllers generated by bindu

// IndexBlog to get all data
func IndexBlog(c *gin.Context) {
	page := c.Params.ByName("page")
	limit := 10
	var db = db.DB
	var blogs []models.Blog
	db.Preload("User").Preload("Comments").Find(&blogs).Offset(page).Limit(limit)

	c.JSON(200, blogs)
}

// ShowBlog to get single data
func ShowBlog(c *gin.Context) {
	id := c.Params.ByName("id")
	var db = db.DB
	var blog models.Blog
	db.Where("id=?",id).Preload("User").Preload("Comments").Find(&blog)

	c.JSON(200, blog)
}

// CreateBlog to a new data
func CreateBlog(c *gin.Context) {
	var db = db.DB
	var blog models.Blog
	c.BindJSON(&blog)
	db.Create(&blog)

	c.JSON(200, blog)
}

// UpdateBlog to Update data
func UpdateBlog(c *gin.Context) {
	id := c.Params.ByName("id")
	var db = db.DB
	var blog models.Blog
	var blog2 models.Blog
	c.BindJSON(&blog)
	if err := db.Where("id=?",id).Find(&blog2).Error; err != nil {
		c.JSON(404, blog2)
		return
	}

	db.Model(&blog2).Update(&blog)

	c.JSON(200, blog)
}

// DestroyBlog to delete single data
func DestroyBlog(c *gin.Context) {
	id := c.Params.ByName("id")
	var db = db.DB
	var blog models.Blog
	if err := db.Where("id=?",id).Find(&blog).Error; err != nil {
		c.JSON(404, blog)
		return
	}

	db.Delete(&blog)

	c.JSON(200, blog)
}

